secret_key: "YOUR_SECRET_KEY"
jwt:
  secret: "jwt_super_secret"
  algorithm: "HS256"
  expire_minutes: 30
database:
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  name: payment_db
default_users:
  admin:
    email: "admin@example.com"
    password: "adminpassword"
    full_name: "Admin"
  user:
    email: "user@example.com"
    password: "password"
    full_name: "Test User"
